### jta多数据源配置
spring.jta.atomikos.datasource.db1.xa-data-source-class-name=com.mysql.cj.jdbc.MysqlXADataSource
spring.jta.atomikos.datasource.db1.xa-properties.user=root
spring.jta.atomikos.datasource.db1.xa-properties.password=ENC(zko8y4jnnf084CWe3KItgEx+3gH7MS8YnbIBFzeN1tA=)
spring.jta.atomikos.datasource.db1.xa-properties.url=jdbc:mysql://127.0.0.1:3306/byteKeep?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
spring.jta.atomikos.datasource.db1.unique-resource-name=db1
spring.jta.atomikos.datasource.db1.max-pool-size=10
spring.jta.atomikos.datasource.db1.min-pool-size=1
spring.jta.atomikos.datasource.db1.max-idle-time=30


spring.jta.atomikos.datasource.db2.xa-data-source-class-name=com.mysql.cj.jdbc.MysqlXADataSource
spring.jta.atomikos.datasource.db2.xa-properties.user=root
spring.jta.atomikos.datasource.db2.xa-properties.password=ENC(zko8y4jnnf084CWe3KItgEx+3gH7MS8YnbIBFzeN1tA=)
spring.jta.atomikos.datasource.db2.xa-properties.url=jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
spring.jta.atomikos.datasource.db2.unique-resource-name=db2



# mybatis 配置
#mybatis.mapper-locations=classpath:mappers/*.xml
#mybatis.type-aliases-package=org.wnn.bytekeep.mybatis.entity


#spring.jta.atomikos.properties.log-base-dir: target/tx-logs